Repository redhat-cop/infra.osbuild, pull requests merged in 2023-10, with the labels that each got.

#299 Update execution enviornment to v3
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/299-update-execustion-enviornment-to-v3.yml
  execution-environment.yml
  meta/runtime.yml
Labels: bug

#300 Fix azure pipeline missing tests
  .azure-pipelines/azure-pipelines.yml
Labels: bug

#304 2.3.0 release
  CHANGELOG.rst
  changelogs/archive/2.3.0/267-skip-rpm-ostree&blueprint-when-container.yaml
  changelogs/archive/2.3.0/268-add-logs-to-builder-role.yml
  changelogs/archive/2.3.0/270-add-know-issues-to-readme.yaml
  changelogs/archive/2.3.0/271-add-support-for-rh-satellite.yaml
  changelogs/archive/2.3.0/272-AAP-12547-CI-testing-changes.yml
  changelogs/archive/2.3.0/273-AAP-12547-Add-extra-docs-linting-from-colection_template.yml
  changelogs/archive/2.3.0/284-add-support-for-beta-repo-setup.yaml
  changelogs/archive/2.3.0/289-clean-up-kickstart-post-if-else.yaml
  changelogs/archive/2.3.0/294-fix-builder_kickstart_post-else.yml
  changelogs/archive/2.3.0/295-add-else_builder_kickstart_post.yml
  changelogs/archive/2.3.0/299-update-execustion-enviornment-to-v3.yml
  changelogs/changelog.yaml
  galaxy.yml
Labels: enhancement

#308 fix: concatenate lists without embedding into an outer layer of list
  changelogs/fragments/308-fix-start_compose-idempotency.yaml
  plugins/modules/start_compose.py
  tests/unit/plugins/modules/test_start_compose.py
Labels: bug, test update

#310 Fix: start_compose changed report valid changed depending on whether or not compose was started
  changelogs/fragments/310-fix-start_compose-changed.yaml
  plugins/modules/rhsm_repo_info.py
  plugins/modules/start_compose.py
  tests/unit/plugins/modules/test_start_compose.py
Labels: bug, test update
