Repository redhat-cop/infra.osbuild, pull requests merged in 2023-07, with the labels that each got.

#244 AAP-13838: Remove community.general.random_string dependencies
  changelogs/fragments/244-AAP-13838-Remove-community.general.random_string-dependencies.yml
  tests/utils/playbooks/edge-installer-e2e-test.yml
  tests/utils/playbooks/tasks/cleanup-test-env.yml
Labels: refactor

#246 AAP-13838: Removed community.libvirt and community.crypto references
  changelogs/fragments/244-AAP-13847-Remove-community.general.random_string-dependencies.yml
  changelogs/fragments/246-AAP-13838-Removed-community.libvirt-and-community.crypto-references.yml
  requirements.yml
  tests/utils/playbooks/edge-installer-e2e-test.yml
  tests/utils/playbooks/tasks/cleanup-test-env.yml
  tests/utils/shippable/shippable.sh
Labels: refactor

#247 Fix issue where file needs to be created for VM
  .azure-pipelines/azure-pipelines.yml
  247-Fix-issue-where-file-needs-to-be-created-for-VM
  tests/utils/playbooks/edge-installer-e2e-test.yml
Labels: bug

#248 Typo in virsh list
  changelogs/fragments/248-Typo-in-virsh-list.yml
  tests/utils/playbooks/edge-installer-e2e-test.yml
Labels: bug

#254 Add timeout param to start_compose
  changelogs/fragments/251-add-start-compose-api-timeout-argument.yml
  plugins/module_utils/weldrapiv1.py
  plugins/modules/start_compose.py
  roles/builder/defaults/main.yml
  roles/builder/meta/argument_specs.yaml
  roles/builder/tasks/main.yml
  tests/unit/plugins/modules/test_start_compose.py
Labels: bug, enhancement, waiting for review

#252 AAP-13082: Remove community.general references
  247-Fix-issue-where-file-needs-to-be-created-for-VM
  build_context/_build/requirements.yml
  changelogs/fragments/247-Fix-issue-where-file-needs-to-be-created-for-VM.yml
  changelogs/fragments/249-AAP-13838-Fix-typo-so-e2e-test-can-run.yml
  changelogs/fragments/252-AAP-13082-Remove-community-general-references.yml
  galaxy.yml
  plugins/modules/repository.py
  plugins/modules/rhsm_repo_info.py
  requirements.yml
  roles/builder/tasks/disable_custom_repos.yml
  roles/setup_server/tasks/main.yaml
  tests/integration/targets/compose_type-edge_commit/tasks/main.yml
  tests/integration/targets/compose_type-edge_commit/tasks/setup_fixture.yml
  tests/integration/targets/compose_type-edge_commit/tasks/teardown_fixture.yml
  tests/integration/targets/compose_type-edge_commit/vars/main.yml
  tests/utils/shippable/shippable.sh
Labels: refactor

#259 AAP-12547 Properly list dependencies
  changelogs/fragments/259-AAP-12547-Properly-list-dependencies.yml
  galaxy.yml
  requirements.yml
Labels: bug

#261 AAP-12547: Change mergify method from merge to squash
  .github/mergify.yml
  changelogs/fragments/261-AAP-12547-Change-mergify-method-from-merge-to-squash.yml
Labels: refactor

#262 AAP-12547 prefer podman in ansible-test
  changelogs/fragments/262-AAP-12547-prefer-podman-in-ansible-test.yml
  tests/utils/shippable/shippable.sh
Labels: refactor

#263 Fix fedora.linux_system_roles typo
  .gitignore
  changelogs/fragments/263-fix-fedora.linux_system_roles-typo.yml
  roles/setup_server/tasks/main.yaml
Labels: bug, waiting for review
