Repository redhat-cop/infra.osbuild, pull requests merged in 2023-08, with the labels that each got.

#267 skip rpm-ostree and blueprint when container
  changelogs/fragments/267-skip-rpm-ostree&blueprint-when-container.yaml
  roles/builder/tasks/main.yml
Labels: bug

#270 Add know issues to readme
  README.md
  changelogs/fragments/270-add-know-issues-to-readme.yaml
Labels: bug

#271 Add support for RH Satellite
  changelogs/changelog.yaml
  changelogs/fragments/271-add-support-for-rh-satellite.yaml
  roles/setup_server/README.md
  roles/setup_server/defaults/main.yml
  roles/setup_server/tasks/main.yaml
  roles/setup_server/tasks/setup_rh_satellite_repos.yml
  roles/setup_server/templates/rhel.json.j2
Labels: enhancement, waiting for review

#273 AAP-12547: Add extra-docs-linting from collection_template
  .github/workflows/extra-docs-linting.yml
  .github/workflows/yamllint_blue.yml
  .github/workflows/yamllint_green.yml
  changelogs/fragments/273-AAP-12547-Add-extra-docs-linting-from-colection_template.yml
  plugins/module_utils/weldrapiv1.py
  roles/builder/meta/argument_specs.yaml
Labels: enhancement

#284 Add support for beta repos - appstream & baseos
  changelogs/fragments/284-add-support-for-beta-repo-setup.yaml
  roles/setup_server/README.md
  roles/setup_server/defaults/main.yml
  roles/setup_server/tasks/main.yaml
Labels: enhancement
