Repository redhat-cop/infra.osbuild, pull requests merged in 2023-06, with the labels that each got.

#186 Added Code of Conduct
  .github/CODE_OF_CONDUCT.md
  README.md
Labels: documentation

#188 AAP-12859 first cut at markdown lint fixes
  plugins/README.md
  roles/builder/README.md
  roles/populate_aap/README.md
  roles/setup_server/README.md
  roles/system_info/README.md
  roles/update_system/README.md
Labels: bug

#189 APP-12867: Add yamlint github action
  workflows/yamllint.yml
Labels: enhancement

#190 Corrected location for github action
  .github/workflows/yamllint.yml
Labels: bug

#191 AAP-12882 fix yamllint line-length too long
  .github/workflows/yamllint.yml
Labels: bug

#192 Switch to blue/green configuration and match edge-api
  .github/workflows/yamllint_blue.yml
  .github/workflows/yamllint_green.yml
Labels: enhancement

#193 AAP-12897 sync yamllint blue-green and increase line-length to 350
  .github/workflows/yamllint_blue.yml
Labels: enhancement

#195 AAP-12916: Reduce yamllint max line length from 350 to 250
  .github/workflows/yamllint_green.yml
  roles/builder/meta/argument_specs.yaml
  roles/builder/tasks/main.yml
Labels: enhancement

#196 AAP-12918 Point mergify rules to yamllint green
  .github/mergify.yml
  .github/workflows/yamllint_blue.yml
  .github/workflows/yamllint_green.yml
Labels: enhancement

#197 AAP-12924: Changed line length from 250 to 200
  .github/dependabot.yml
  .github/mergify.yml
  .github/workflows/yamllint_blue.yml
  .github/workflows/yamllint_green.yml
  roles/builder/defaults/main.yml
  roles/builder/meta/argument_specs.yaml
  roles/builder/tasks/main.yml
  roles/builder/vars/main.yml
  tests/integration/targets/compose_type-ami/vars/main.yml
  tests/integration/targets/compose_type-container/vars/main.yml
  tests/integration/targets/compose_type-edge_commit/vars/main.yml
  tests/integration/targets/compose_type-edge_container/vars/main.yml
  tests/integration/targets/compose_type-edge_installer/vars/main.yml
  tests/integration/targets/compose_type-edge_raw_image/vars/main.yml
  tests/integration/targets/compose_type-edge_simplified_installer/vars/main.yml
  tests/integration/targets/compose_type-image_installer/vars/main.yml
  tests/integration/targets/compose_type-iot_commit/vars/main.yml
  tests/integration/targets/compose_type-iot_container/vars/main.yml
  tests/integration/targets/compose_type-iot_installer/vars/main.yml
  tests/integration/targets/compose_type-iot_raw_image/vars/main.yml
  tests/integration/targets/compose_type-oci/vars/main.yml
  tests/integration/targets/compose_type-openstack/vars/main.yml
  tests/integration/targets/compose_type-qcow2/vars/main.yml
  tests/integration/targets/compose_type-tar/vars/main.yml
  tests/integration/targets/compose_type-vhd/vars/main.yml
  tests/integration/targets/compose_type-vmdk/vars/main.yml
  tests/integration/targets/role_builder/vars/main.yml
Labels: refactor

#199 AAP-12972: Add some positive tests and many negative test stubs for w…
  tests/unit/plugins/module_utils/test_weldrapiv1.py
Labels: test update

#200 Aws support
  requirements.yml
  roles/builder/defaults/main.yml
  roles/builder/tasks/main.yml
  roles/builder/vars/main.yml
  tests/utils/shippable/shippable.sh
Labels: question

#201 AAP-13079: Add security policy and fix some lint/dependency issues
  SECURITY.md
  galaxy.yml
  roles/builder/tasks/main.yml
  roles/builder/vars/main.yml
Labels: bug, enhancement

#203 AAP-13106 - Change mergify rules to support "changes requested" label…
  .github/mergify.yml
  .github/workflows/yamllint_blue.yml
Labels: enhancement

#204 AAP-13107: Fix bug in new changes request mergifyio rule
  .github/mergify.yml
Labels: bug

#205 Per validation requirements, added license to README.md
  README.md
Labels: documentation

#206 AAP-12970: Validation requirement: Add required versions
  README.md
Labels: documentation

#207 AAP-13147: Add OpenSSF Scorecard Badge
  README.md
Labels: enhancement

#208 AAP-13148: Create scorecard.yml
  .github/workflows/scorecard.yml
Labels: enhancement

#210 AAP-13167: Fix one OpenSSF badge, add another, yamllint fixes
  .github/workflows/scorecard.yml
  README.md
Labels: bug, enhancement

#202 Surveyys
  roles/populate_aap/defaults/main.yml
  roles/populate_aap/template_surveys/builder_survey.yml
Labels: waiting for review

#211 AAP-13181 Add contributing section to README
  README.md
Labels: documentation

#212 Add builder_image_path var that is returned at end of builder role
  roles/builder/README.md
  roles/builder/tasks/main.yml
Labels: enhancement

#214 Improper file extension
  playbooks/osbuild_system_info.yml
Labels: bug

#222 Add changelog fragment require to the checklist
  .github/pull_request_template.md
  changelogs/fragments/222-add-changelog-fragment-require-to-the-checklist.yaml
Labels: documentation

#220 Add missing changelog fragments for 1.0.0 release
  .azure-pipelines/azure-pipelines.yml
  .github/pull_request_template.md
  changelogs/fragments/1-added-builder-role.yaml
  changelogs/fragments/10-Fix-image-permissions.yaml
  changelogs/fragments/11-created-variable-for-the-compose-type.yaml
  changelogs/fragments/12-Create-role-for-an-http-server-to-host-images.yaml
  changelogs/fragments/13-fix-sanity-tests-for-core-2-15-branch.yaml
  changelogs/fragments/17-refactor-image-server-role-to-use-blocks-for-logic-grouping.yaml
  changelogs/fragments/19-initial-remote-integration-tests-setup.yaml
  changelogs/fragments/2-Added-Superlinter-and-fixed-linting-issues.yaml
  changelogs/fragments/20-Fix-fedora-support--improve-unsupported-image-err.yaml
  changelogs/fragments/22-Updated-docs-and-fixed-outstanding-issues.yaml
  changelogs/fragments/23-Ci-test-prep-build-server.yaml
  changelogs/fragments/29-Correct-galaxy-yml-metadata.yaml
  changelogs/fragments/3-Corrected-typo-in-variable-name.yaml
  changelogs/fragments/30-add-dependencies-that-we-ve-picked-up-along-the-way.yaml
  changelogs/fragments/31-fix-module-name.yaml
  changelogs/fragments/32-Update-README-md.yaml
  changelogs/fragments/33-add-tests-for-builder-role.yaml
  changelogs/fragments/34-add-proper-output-type-for-compose-type.yaml
  changelogs/fragments/35-enable-integration-tests-for-rhel8-x.yaml
  changelogs/fragments/36-Add-custom-repo-functionality.yaml
  changelogs/fragments/39-drop-support-for-depricated-compose-types.yaml
  changelogs/fragments/4-Added-isort-configuration-so-superlinter-does-not-fail-on-libs-that-are-not-in-the-superlinter-container.yaml
  changelogs/fragments/41-Fix-custom-package-image-build.yaml
  changelogs/fragments/42-Ansible-lint-cleanup.yaml
  changelogs/fragments/43-WIP--enable-ansible-lint---profile-production-for-sanity-tests.yaml
  changelogs/fragments/44-added-versions-and-updates.yaml
  changelogs/fragments/46-move-to-infra-osbuild-name-for-inclusion-as-Validated-Content.yaml
  changelogs/fragments/47-Delete-inventory-ini.yaml
  changelogs/fragments/48-Add-rhsm-option---update-source-repo-if-it-already-exists.yaml
  changelogs/fragments/49-missed-a-couple-rename-items-in-the-migration.yaml
  changelogs/fragments/5-Azure-pipelines.yaml
  changelogs/fragments/50-missed-a-couple-rename-items-in-the-migration.yaml
  changelogs/fragments/6-Fix-sanity-tests.yaml
  changelogs/fragments/7-Fixed-typo-in-method-call.yaml
  changelogs/fragments/8-Make-pubkey-a-var.yaml
  changelogs/fragments/9-fix-image-permissions-issue.yaml
  changelogs/temp/106-kickstart-post-omit.yaml
  changelogs/temp/107-kickstart-validation.yaml
  changelogs/temp/116-image-storage-check.yaml
  changelogs/temp/123-change-temp-iso-name.yaml
  changelogs/temp/126-get-job-id.yaml
  changelogs/temp/132-aap-vars-fix.yaml
  changelogs/temp/138-update-ssh-user-pass.yaml
  changelogs/temp/139-compose-wait-timeout.yaml
  changelogs/temp/142-cli-env-arg.yaml
  changelogs/temp/150-fix-multiple-yum-repo-files.yaml
  changelogs/temp/172-get-system-info.yaml
  changelogs/temp/175-update-systems.yaml
  galaxy.yml
  tests/utils/shippable/lint.sh
  tests/utils/shippable/remote.sh
Labels: documentation, test update, waiting for review

#229 AAP-13280: Converted 1.0.0 fragments to release notes
  .gitignore
  CHANGELOG.rst
  changelogs/archive/1.0.0/1-added-builder-role.yaml
  changelogs/archive/1.0.0/1.0.0_release_summary.yaml
  changelogs/archive/1.0.0/10-Fix-image-permissions.yaml
  changelogs/archive/1.0.0/11-created-variable-for-the-compose-type.yaml
  changelogs/archive/1.0.0/12-Create-role-for-an-http-server-to-host-images.yaml
  changelogs/archive/1.0.0/13-fix-sanity-tests-for-core-2-15-branch.yaml
  changelogs/archive/1.0.0/17-refactor-image-server-role-to-use-blocks-for-logic-grouping.yaml
  changelogs/archive/1.0.0/19-initial-remote-integration-tests-setup.yaml
  changelogs/archive/1.0.0/2-Added-Superlinter-and-fixed-linting-issues.yaml
  changelogs/archive/1.0.0/20-Fix-fedora-support--improve-unsupported-image-err.yaml
  changelogs/archive/1.0.0/22-Updated-docs-and-fixed-outstanding-issues.yaml
  changelogs/archive/1.0.0/23-Ci-test-prep-build-server.yaml
  changelogs/archive/1.0.0/29-Correct-galaxy-yml-metadata.yaml
  changelogs/archive/1.0.0/3-Corrected-typo-in-variable-name.yaml
  changelogs/archive/1.0.0/30-add-dependencies-that-we-ve-picked-up-along-the-way.yaml
  changelogs/archive/1.0.0/31-fix-module-name.yaml
  changelogs/archive/1.0.0/32-Update-README-md.yaml
  changelogs/archive/1.0.0/33-add-tests-for-builder-role.yaml
  changelogs/archive/1.0.0/34-add-proper-output-type-for-compose-type.yaml
  changelogs/archive/1.0.0/35-enable-integration-tests-for-rhel8-x.yaml
  changelogs/archive/1.0.0/36-Add-custom-repo-functionality.yaml
  changelogs/archive/1.0.0/39-drop-support-for-depricated-compose-types.yaml
  changelogs/archive/1.0.0/4-Added-isort-configuration-so-superlinter-does-not-fail-on-libs-that-are-not-in-the-superlinter-container.yaml
  changelogs/archive/1.0.0/41-Fix-custom-package-image-build.yaml
  changelogs/archive/1.0.0/42-Ansible-lint-cleanup.yaml
  changelogs/archive/1.0.0/43-WIP--enable-ansible-lint---profile-production-for-sanity-tests.yaml
  changelogs/archive/1.0.0/44-added-versions-and-updates.yaml
  changelogs/archive/1.0.0/46-move-to-infra-osbuild-name-for-inclusion-as-Validated-Content.yaml
  changelogs/archive/1.0.0/47-Delete-inventory-ini.yaml
  changelogs/archive/1.0.0/48-Add-rhsm-option---update-source-repo-if-it-already-exists.yaml
  changelogs/archive/1.0.0/49-missed-a-couple-rename-items-in-the-migration.yaml
  changelogs/archive/1.0.0/5-Azure-pipelines.yaml
  changelogs/archive/1.0.0/50-missed-a-couple-rename-items-in-the-migration.yaml
  changelogs/archive/1.0.0/6-Fix-sanity-tests.yaml
  changelogs/archive/1.0.0/7-Fixed-typo-in-method-call.yaml
  changelogs/archive/1.0.0/8-Make-pubkey-a-var.yaml
  changelogs/archive/1.0.0/9-fix-image-permissions-issue.yaml
  changelogs/changelog.yaml
  changelogs/config.yaml
  changelogs/temp/222-add-changelog-fragment-require-to-the-checklist.yaml
  galaxy.yml
Labels: documentation

#221 changes e2e tests settings to run on OpenStack
  changelogs/fragments/221-change-e2e-tests-for-openstack.yaml
  tests/utils/playbooks/edge-installer-e2e-test.yml
  tests/utils/playbooks/inventory
  tests/utils/playbooks/tasks/cleanup-test-env.yml
  tests/utils/playbooks/templates/vm-template.xml.j2
Labels: test update, waiting for review

#217 AAP-13348 Fix UnknownUUID ID is not a valid uuid
  changelogs/fragments/217-fix-remove-id-not-valid-uuid.yaml
  roles/builder/tasks/main.yml
Labels: bug, waiting for review

#219 updated readme with included content
  README.md
Labels: waiting for review

#230 AAP-10052 added github workflow to release osbuild collection
  .github/workflows/ah_token_refresh.yml
  .github/workflows/release.yml
  changelogs/fragments/230-github-workflow-release-osbuild-collection.yaml
Labels: enhancement

#232 2.0.0 Release notes
  .github/workflows/ah_token_refresh.yml
  CHANGELOG.rst
  changelogs/archive/2.0.0/100-Fix-disable-repos-rhsm.yaml
  changelogs/archive/2.0.0/101-Remove-no-log.yaml
  changelogs/archive/2.0.0/104-Build-TOML-data-as-dict-instead-of-string.yaml
  changelogs/archive/2.0.0/105-Add-always-block-to-disable-repos-after-block.yaml
  changelogs/archive/2.0.0/106-Fix-kickstart-post-omit-issue.yaml
  changelogs/archive/2.0.0/107-added-basic-kickstart-validation--fixed-sshkey-error.yaml
  changelogs/archive/2.0.0/109-changed-default-size-from-8-to-0.yaml
  changelogs/archive/2.0.0/110-Fix-when-enable-disable-rhsm-repos.yaml
  changelogs/archive/2.0.0/112-Fix-issues-from-ansible-lint-6-14-0.yaml
  changelogs/archive/2.0.0/113-Bump-version-number-in-galaxy-yml-for-2-0-0-release.yaml
  changelogs/archive/2.0.0/2.0.0_release_summary.yaml
  changelogs/archive/2.0.0/217-fix-remove-id-not-valid-uuid.yaml
  changelogs/archive/2.0.0/221-change-e2e-tests-for-openstack.yaml
  changelogs/archive/2.0.0/230-github-workflow-release-osbuild-collection.yaml
  changelogs/archive/2.0.0/52-fix-ci-lint.yaml
  changelogs/archive/2.0.0/53-define-execution-environment.yaml
  changelogs/archive/2.0.0/54-Add-Role-to-Create--edge-installer--Type-Images.yaml
  changelogs/archive/2.0.0/55-updated-documentation-to-explain-how-to-call-different-build-types.yaml
  changelogs/archive/2.0.0/56-Update-testbuild-playbook-to-new-build-flow.yaml
  changelogs/archive/2.0.0/57-Add-kickstart.yaml
  changelogs/archive/2.0.0/58-Handle-cross-distro-composes--change-test-cases-to-validate-it.yaml
  changelogs/archive/2.0.0/59-Add-distro-default-omit.yaml
  changelogs/archive/2.0.0/60-Support-Building-Images-on-ostree-Based-OSes.yaml
  changelogs/archive/2.0.0/62-merge-edge-installer-builder-and-builder-role--added-kickstart-vars.yaml
  changelogs/archive/2.0.0/63-add-builder-role-docs.yaml
  changelogs/archive/2.0.0/65-update-README.yaml
  changelogs/archive/2.0.0/66-Fix-compose-types.yaml
  changelogs/archive/2.0.0/67-switch-to-allowing-more-than-one-custom-repo-or-zero-custom-repos.yaml
  changelogs/archive/2.0.0/68-Add-test-for-all-compose-types.yaml
  changelogs/archive/2.0.0/75-Fix-customizations-single-and-double-brackets.yaml
  changelogs/archive/2.0.0/76-update-OS-versions-in-ci-devel-tests.yaml
  changelogs/archive/2.0.0/78-added-python36-package-for-minimal-systems.yaml
  changelogs/archive/2.0.0/80-don-t-lock-on-old-version-of-anislbe-lint--issue-was-fixed-and-release.yaml
  changelogs/archive/2.0.0/81-Try-to-find-our-compose-heuristically-if-weldr-times-out.yaml
  changelogs/archive/2.0.0/82-Refactor-to-enable-rpm-ostree-ISO-installer-builds.yaml
  changelogs/archive/2.0.0/83-Remove-aap-defaults--conditionally-create-aap-playbook-in-ks.yaml
  changelogs/archive/2.0.0/84-warn-if-sshkey-file-is-undefined--add-user-password-for-kickstart--update-README.yaml
  changelogs/archive/2.0.0/86-Update-kickstart-template-to-add-more-customizable.yaml
  changelogs/archive/2.0.0/88-updated-kickstart-to-prevent-insufficient-kickstart-message.yaml
  changelogs/archive/2.0.0/89-Add-custom-kickstart.yaml
  changelogs/archive/2.0.0/90-Skip-update-repo-if-needed.yaml
  changelogs/archive/2.0.0/91-fixed-issue-if-hostname-is-provided-instead-of-ip-address.yaml
  changelogs/archive/2.0.0/93-Update-inject-ks-and-add-to-builder-role-to-inject-ks-to-iso.yaml
  changelogs/archive/2.0.0/99-Add-support-for-rhsm-repos.yaml
  changelogs/changelog.yaml
  tests/utils/shippable/lint.sh
Labels: documentation

#235 Turn off release to Automation Hub
  .github/workflows/release.yml
  changelogs/fragments/235-turn-off-release-ah.yml
Labels: refactor

#234 AAP-13549 added testing policy section to the README and test checklist
  .github/pull_request_template.md
  README.md
  changelogs/fragments/234-testing-policy-readme-and-test-checklist.yml
Labels: documentation

#242 Chris found the version number was wrong
  galaxy.yml
Labels: bug
