Repository redhat-cop/infra.osbuild, pull requests merged in 2024-07, with the labels that each got.

#392 Add [[container]] section in generated blueprint to support embedded container images
  CHANGELOG.rst
  blueprints/rhel-9-latest-HIPAA.toml
  galaxy.yml
  plugins/modules/create_blueprint.py
  roles/builder/README.md
  roles/builder/meta/argument_specs.yaml
  roles/builder/tasks/main.yml
  tests/unit/plugins/modules/test_create_blueprint.py
Labels: enhancement, waiting for review

#403 Add FIPS support to ISO installer
  roles/builder/tasks/main.yml
Labels: enhancement

#402 Update extra-docs-linting.yml
  .github/workflows/extra-docs-linting.yml
Labels: invalid, approved, waiting for review
